# See LICENSE for license details.

#*****************************************************************************
# fminm.S
#-----------------------------------------------------------------------------
#
# Test f{min|max}m.d instructinos.
#

#include "riscv_test.h"
#include "test_macros.h"

RVTEST_RV64UF
RVTEST_CODE_BEGIN

#if __riscv_xlen == 32
    # Replace the function with the 32-bit variant defined in test_macros.h
    #undef TEST_FP_OP2_D
    #define TEST_FP_OP2_D TEST_FP_OP2_D32
#endif

  #-------------------------------------------------------------
  # Arithmetic tests
  #-------------------------------------------------------------

  TEST_FP_OP2_D( 2,  fminm.d, 0,        1.0,        2.5,        1.0 );
  TEST_FP_OP2_D( 3,  fminm.d, 0,    -1235.1,    -1235.1,        1.1 );
  TEST_FP_OP2_D( 4,  fminm.d, 0,    -1235.1,        1.1,    -1235.1 );
  TEST_FP_OP2_D( 5,  fminm.d, 0,       qNaN,        NaN,    -1235.1 );
  TEST_FP_OP2_D( 6,  fminm.d, 0, 0.00000001, 3.14159265, 0.00000001 );
  TEST_FP_OP2_D( 7,  fminm.d, 0,       -2.0,       -1.0,       -2.0 );

  TEST_FP_OP2_D(12,  fmaxm.d, 0,        2.5,        2.5,        1.0 );
  TEST_FP_OP2_D(13,  fmaxm.d, 0,        1.1,    -1235.1,        1.1 );
  TEST_FP_OP2_D(14,  fmaxm.d, 0,        1.1,        1.1,    -1235.1 );
  TEST_FP_OP2_D(15,  fmaxm.d, 0,       qNaN,        NaN,    -1235.1 );
  TEST_FP_OP2_D(16,  fmaxm.d, 0, 3.14159265, 3.14159265, 0.00000001 );
  TEST_FP_OP2_D(17,  fmaxm.d, 0,       -1.0,       -1.0,       -2.0 );

  # FMAX(sNaN, x) = canonical NaN
  TEST_FP_OP2_D(20,  fmaxm.d, 0x10, qNaN, sNaN, 1.0);
  # FMAX(qNaN, qNaN) = canonical NaN
  TEST_FP_OP2_D(21,  fmaxm.d, 0x00, qNaN,  NaN, NaN);

  # -0.0 < +0.0
  TEST_FP_OP2_D(30,  fminm.d, 0,       -0.0,       -0.0,        0.0 );
  TEST_FP_OP2_D(31,  fminm.d, 0,       -0.0,        0.0,       -0.0 );
  TEST_FP_OP2_D(32,  fmaxm.d, 0,        0.0,       -0.0,        0.0 );
  TEST_FP_OP2_D(33,  fmaxm.d, 0,        0.0,        0.0,       -0.0 );

  TEST_PASSFAIL

RVTEST_CODE_END

  .data
RVTEST_DATA_BEGIN

  TEST_DATA

RVTEST_DATA_END
